
CREATE TABLE IF NOT EXISTS `spring_session` (
	`PRIMARY_ID` CHAR(36) NOT NULL COLLATE 'latin1_swedish_ci',
	`SESSION_ID` CHAR(36) NOT NULL COLLATE 'latin1_swedish_ci',
	`CREATION_TIME` BIGINT(20) NOT NULL,
	`LAST_ACCESS_TIME` BIGINT(20) NOT NULL,
	`MAX_INACTIVE_INTERVAL` INT(11) NOT NULL,
	`EXPIRY_TIME` BIGINT(20) NOT NULL,
	`PRINCIPAL_NAME` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`PRIMARY_ID`) USING BTREE,
	UNIQUE INDEX `SPRING_SESSION_IX1` (`SESSION_ID`) USING BTREE,
	INDEX `SPRING_SESSION_IX2` (`EXPIRY_TIME`) USING BTREE,
	INDEX `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;

CREATE TABLE IF NOT EXISTS `spring_session_attributes` (
	`SESSION_PRIMARY_ID` CHAR(36) NOT NULL COLLATE 'latin1_swedish_ci',
	`ATTRIBUTE_NAME` VARCHAR(200) NOT NULL COLLATE 'latin1_swedish_ci',
	`ATTRIBUTE_BYTES` BLOB NOT NULL,
	PRIMARY KEY (`SESSION_PRIMARY_ID`, `ATTRIBUTE_NAME`) USING BTREE,
	CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_PRIMARY_ID`) REFERENCES `spring_session` (`PRIMARY_ID`) ON UPDATE RESTRICT ON DELETE CASCADE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;

-- Password 9l68{FoG|H#9qEI]
INSERT INTO users(username, password, enabled, creation_date) values("ManhattanAdmin", "$2a$10$/8vKyAcD4KzWPyOIPG4kMezPiZO7feWxMC0FADuca/X8s8oJcuYvu", 1, "2024-01-15 14:30:00");

INSERT INTO authorities(username, authority) values(1, "Admin");


